module.exports ={
    APPLICATION_ERROR: 500,
    AUTHENTICATION_FAILED: 511,
    EMAIL_ALREADY_EXISTS: 512,
    PERMISSION_DENIED: 513,

    INVALID_FULL_NAME: 411,
    INVALID_USERNAME: 412,
    INVALID_PASSWORD: 413,
    PASSWORD_LENGTH_REQUIRE: 414,
    USERNAME_ALREADY_EXISTS: 415,
    USERNAME_LENGTH_REQUIRE: 416,
    WRONG_EMAIL_FORMAT: 417,

    GOOGLE_VERIFY_FAILED: 601,
    FACEBOOK_VERIFY_FAILED: 602,

    NOTE_NOT_FOUND: 701,
    TRANSACTION_NOT_FOUND: 702,
    MEMBER_NOTE_NOT_EMPTY: 703,
    TRANSACTION_COMPLETED: 704
}