module.exports ={
    APPLICATION_ERROR: 500,
    AUTHENTICATION_FAILED: 511,
    EMAIL_ALREADY_EXISTS: 512,

    INVALID_FULL_NAME: 411,
    INVALID_USERNAME: 412,
    PASSWORD_LENGTH_REQUIRE: 413,
    USERNAME_ALREADY_EXISTS: 414,
    USERNAME_LENGTH_REQUIRE: 415,
    WRONG_EMAIL_FORMAT: 415,

    GOOGLE_VERIFY_FAILED: 601,
    FACEBOOK_VERIFY_FAILED: 602
}